defaults:
  - model: hifigan
  - writer: cometml
  - metrics: empty
  - datasets: ljspeech
  - dataloader: default
  - transforms: default
  - loss: hifigan
  - _self_

optimizer_g:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]

optimizer_d:
  _target_: torch.optim.AdamW
  lr: 2e-4
  betas: [0.8, 0.99]

lr_scheduler_g:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.99999

lr_scheduler_d:
  _target_: torch.optim.lr_scheduler.ExponentialLR
  gamma: 0.99999

loss_function:
  _target_: src.loss.HiFiGANLoss
  audio_to_mel:
    _target_: src.text_to_mel.DeterministicModel

trainer:
  _target_: src.trainer.gan_trainer.GANTrainer
  log_step: 50
  n_epochs: 100
  epoch_len: null
  device_tensors: ["audio", "mel"] # which tensors should be on device (ex. GPU)
  resume_from: null # null or path to the checkpoint dir with *.pth and config.yaml
  device: auto # device name or "auto"
  override: False # if True, will override the previous run with the same name
  monitor: "off" # "off" or "max/min metric_name", i.e. our goal is to maximize/minimize metric
  save_period: 5 # checkpoint each save_period epochs in addition to the best epoch
  early_stop: ${trainer.n_epochs} # epochs for early stopping
  save_dir: "saved"
  max_grad_norm: 5.0
  seed: 1
